# Generated by Django 6.0.5 on 2026-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("apellido", models.CharField(blank=True, default="", max_length=120)),
                ("telefono", models.CharField(max_length=30)),
                ("direccion", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MAYORISTA", "Mayorista"),
                            ("MINORISTA", "Minorista"),
                        ],
                        default="MINORISTA",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre", "apellido"],
            },
        ),
    ]
