# Generated by Django 6.0.5 on 2026-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
