# Generated by Django 6.0.5 on 2026-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("activo", True)),
                fields=("nombre", "apellido"),
                name="unique_cliente_nombre_apellido_activo",
            ),
        ),
    ]
