# Generated by Django 6.0.5 on 2026-09-29 02:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Galpon",
            fields=[
                (
                    "numero_galpon",
                    models.PositiveIntegerField(
                        help_text="Número identificador único del galpón.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "capacidad_maxima",
                    models.PositiveIntegerField(
                        help_text="Capacidad física total de aves en el galpón.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "cantidad_inicial_gallinas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Población con la que inició el lote del galpón.",
                    ),
                ),
                (
                    "cantidad_actual_gallinas",
                    models.PositiveIntegerField(
                        default=0, help_text="Población viva actual en el galpón."
                    ),
                ),
                ("descripcion_galpon", models.TextField(blank=True, default="")),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Galpón",
                "verbose_name_plural": "Galpones",
                "ordering": ["numero_galpon"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_actual_gallinas__gte", 0)),
                        name="check_galpon_gallinas_no_negativas",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("capacidad_maxima__gt", 0)),
                        name="check_galpon_capacidad_positiva",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "huevos_rotos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Huevos rotos o mermas registradas en unidades individuales.",
                    ),
                ),
                (
                    "total_maples",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total acumulado de maples comerciales ingresados en la jornada.",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "galpon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_produccion",
                        to="produccion.galpon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Producción",
                "verbose_name_plural": "Registros de Producción",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoGallina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("SALIDA", "Salida")],
                        max_length=10,
                    ),
                ),
                (
                    "motivo_movimiento",
                    models.CharField(
                        choices=[
                            ("MUERTE", "Mortalidad / Muerte"),
                            ("VENTA", "Venta"),
                            ("REHABILITACION", "Rehabilitación / Aislamiento"),
                            ("COMPRA", "Compra / Incorporación"),
                            ("RECUPERADA", "Recuperadas"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_gallinas",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "descripcion_movimiento",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "galpon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_gallinas",
                        to="produccion.galpon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Gallinas",
                "verbose_name_plural": "Movimientos de Gallinas",
                "ordering": ["-fecha", "-creado_en"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_gallinas__gt", 0)),
                        name="check_cantidad_movimiento_gallinas_positiva",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemProduccionHuevo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_huevo",
                    models.CharField(
                        choices=[
                            ("BLANCO_1", "Blanco 1"),
                            ("BLANCO_2", "Blanco 2"),
                            ("COLOR_1", "Color 1"),
                            ("COLOR_2", "Color 2"),
                            ("MIXTO", "Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_huevos",
                    models.PositiveIntegerField(
                        help_text="Cantidad de huevos individuales persistida (30 unidades por maple).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="produccion.registroproduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Producción de Huevo",
                "verbose_name_plural": "Items de Producción de Huevos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registro", "tipo_huevo"),
                        name="unique_registro_tipo_huevo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_huevos__gt", 0)),
                        name="check_cantidad_huevos_produccion_positiva",
                    ),
                ],
            },
        ),
    ]
