# Generated by Django 6.0.5 on 2026-09-11 02:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Galpon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("capacidad_maxima", models.PositiveIntegerField(default=1800)),
                ("cantidad_actual_gallinas", models.PositiveIntegerField(default=1800)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Galpón",
                "verbose_name_plural": "Galpones",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="StockHuevo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_huevo",
                    models.CharField(
                        choices=[
                            ("BLANCO_1", "Blanco 1"),
                            ("BLANCO_2", "Blanco 2"),
                            ("COLOR_1", "Color 1"),
                            ("COLOR_2", "Color 2"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "cantidad_disponible",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de unidades comerciales aptas disponibles en depósito.",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock de Huevos",
                "verbose_name_plural": "Stock de Huevos",
            },
        ),
        migrations.CreateModel(
            name="ProduccionDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_huevo",
                    models.CharField(
                        choices=[
                            ("BLANCO_1", "Blanco 1"),
                            ("BLANCO_2", "Blanco 2"),
                            ("COLOR_1", "Color 1"),
                            ("COLOR_2", "Color 2"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_huevos",
                    models.PositiveIntegerField(
                        help_text="Huevos comerciales aptos (en unidades: maples * 30).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cantidad_huevos_rotos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Huevos no comerciales por roturas o anomalías (unidades).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fecha",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "galpon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones",
                        to="produccion.galpon",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Producción Diaria",
                "verbose_name_plural": "Producciones Diarias",
                "ordering": ["-fecha", "-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["fecha", "galpon"], name="produccion__fecha_bb2345_idx"
                    ),
                    models.Index(
                        fields=["tipo_huevo", "fecha"],
                        name="produccion__tipo_hu_5aaca7_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_huevos__gte", 0)),
                        name="check_produccion_cantidad_huevos_positiva",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_huevos_rotos__gte", 0)),
                        name="check_produccion_huevos_rotos_positiva",
                    ),
                ],
            },
        ),
    ]
