# Generated by Django 6.0.5 on 2026-10-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0002_alter_movimientogallina_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientogallina",
            name="descripcion_movimiento",
            field=models.CharField(
                help_text="Detalle o motivo específico del movimiento de aves.",
                max_length=255,
            ),
        ),
    ]
