# Generated by Django 6.0.5 on 2026-10-08 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0003_alter_movimientogallina_descripcion_movimiento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientogallina",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_gallinas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
