# Generated by Django 6.0.5 on 2026-09-07 02:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_alter_cliente_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_entrega",
                    models.CharField(
                        choices=[("JUEVES", "Jueves"), ("VIERNES", "Viernes")],
                        default="JUEVES",
                        max_length=10,
                    ),
                ),
                ("estado_pago", models.BooleanField(db_index=True, default=False)),
                ("estado_entrega", models.BooleanField(db_index=True, default=False)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_huevo",
                    models.CharField(
                        choices=[
                            ("BLANCO_1", "Blanco 1"),
                            ("BLANCO_2", "Blanco 2"),
                            ("COLOR_1", "Color 1"),
                            ("COLOR_2", "Color 2"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_unidades",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Items de Pedido",
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["estado_pago", "estado_entrega"],
                name="pedidos_ped_estado__a236b2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.UniqueConstraint(
                fields=("pedido", "tipo_huevo"), name="unique_pedido_tipo_huevo"
            ),
        ),
        migrations.AddConstraint(
            model_name="itempedido",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_unidades__gt", 0)),
                name="check_cantidad_unidades_positiva",
            ),
        ),
    ]
