# Generated by Django 6.0.5 on 2026-09-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="tipo_huevo",
            field=models.CharField(
                choices=[
                    ("BLANCO_1", "Blanco 1"),
                    ("BLANCO_2", "Blanco 2"),
                    ("COLOR_1", "Color 1"),
                    ("COLOR_2", "Color 2"),
                    ("MIXTO", "Mixto"),
                ],
                max_length=20,
            ),
        ),
    ]
