# Generated by Django 6.0.5 on 2026-10-08 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PEDIDOS_DEL_DIA", "Pedidos del Día"),
                            ("MOVIMIENTO_GALLINAS", "Movimiento de Gallinas"),
                            ("SISTEMA", "Sistema"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("mensaje", models.CharField(max_length=255)),
                ("leida", models.BooleanField(db_index=True, default=False)),
                (
                    "ruta",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ruta SPA interna para redirección al interactuar con la notificación.",
                        max_length=200,
                    ),
                ),
                (
                    "fecha_referencia",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Garantiza idempotencia en notificaciones diarias de sistema.",
                        null=True,
                    ),
                ),
                ("datos_extra", models.JSONField(blank=True, default=dict)),
                ("creada_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-creada_en"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "leida", "-creada_en"],
                        name="notificacio_usuario_9b2c76_idx",
                    ),
                    models.Index(
                        fields=["usuario", "tipo", "fecha_referencia"],
                        name="notificacio_usuario_29a44a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("fecha_referencia__isnull", False)),
                        fields=("usuario", "tipo", "fecha_referencia"),
                        name="unique_notificacion_diaria_por_usuario",
                    )
                ],
            },
        ),
    ]
