# Generated by Django 6.0.5 on 2026-08-16 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ALIMENTO", "Alimento"),
                            ("COMBUSTIBLE", "Combustible"),
                            ("INSUMOS", "Insumos Veterinarios"),
                            ("MANTENIMIENTO", "Mantenimiento / Ferretería"),
                            ("LIMPIEZA", "Artículos de Limpieza"),
                            ("OTROS", "Otros"),
                        ],
                        default="OTROS",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
    ]
