# Generated by Django 6.0.5 on 2026-09-30 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
